### ISSUE TITLE
indentexpr for switch case behaviour

### ISSUE THREAD

**Issue by echoface** [tree-sitter/tree-sitter-go#102]
nvim 0.8.1
nvim-treesitter: latest
indent behaviour wrong

details:

case 1: enable nvim-treesitter with go support
set indentexpr?  output =>     indentexpr=nvim_treesitter#indent()
```go
func abc(v int) {
    switch v {
}
    switch {
}
    for {
        switch {
    }
    }
}

```

case 2: disable nvim-treesitter, everything going on well: (ps: filetype indent on)
```go
func abc(v int) {
    switch v {

    }
    switch {
    }
    for {
        switch {
        }
    }
}
```
set indentexpr?  output =>     indentexpr=GoIndent(v:lnum)

**Comment by amaanq** [comment]
That's an issue for nvim-treesitter, not tree-sitter-go
