### ISSUE TITLE
Differentiate symbols mentioned as the first phrase of a comment string

### ISSUE THREAD

**Issue by weakphish** [tree-sitter/tree-sitter-go#108]
Copied from https://github.com/helix-editor/helix/issues/5909

In Go, the standard idiom is to begin docstrings with the name of the symbol being described, like so:
```go
// foo performs an action
func foo() {
    fmt.Println("bar")
}

// Bar is a struct
type Bar struct {
    baz int 
}
```
I propose that, similar to Goland from Jetbrains, the first term of a Go docstring be differentiated.

**Comment by amaanq** [comment]
Can be done with queries

**Comment by kackerx** [comment]
There is also the interface of go, ts can't recognize it, how to use the query, ,
