### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by smoelius** [tree-sitter/tree-sitter-go#127]
Would it be a huge imposition to include a changelog in this repository?

For example, I noticed that version 0.20.0 added `expression_statement` nodes: https://github.com/tree-sitter/tree-sitter-go/blob/bbaa67a180cfe0c943e50c55130918be8efb20bd/grammar.js#L487

Listing such changes conspicuously somewhere would be helpful to users.

**Comment by amaanq** [comment]
it'd be nice, and ideally automated, though Max prefers not to use actions like release-please to automate this. Do you have any suggestions to ease the burden? (I don't want to manually write changelogs for 10+ grammars)

**Comment by smoelius** [comment]
I haven't used this feature myself, but GitHub can automatically generate "release notes" (see lower right of the following image): <img width="1166" alt="Screenshot 2023-08-03 at 8 17 50 AM" src="https://github.com/tree-sitter/tree-sitter-go/assets/35515885/a8461dc2-11a8-46a3-aac1-e90356c6d4e2">

I think there are advantages to having a project's history in one file (i.e., a changelog).

But having named releases with release notes would be another way of alerting users to changes.

**Comment by amaanq** [comment]
I agree a changelog would be great, but I don't really feel anyone but me would maintain that for every parser, and that's a huge burden for me

I'll see about the release notes, thanks!

**Comment by smoelius** [comment]
> Just created a release with notes, hope that helps!

It does. Thank you.
