### ISSUE TITLE
Constant not being recognized after declaration 

### ISSUE THREAD

**Issue by jaymorelli96** [tree-sitter/tree-sitter-go#131]
Constant seems only to be recognized when declared (const_spec). After it has been declared, it is treated just as a normal keyword.

I am pretty sure this is not mean to be the correct behavior? It seems impossible to change the highlight group for a constant that has already being declared.

![image](https://github.com/tree-sitter/tree-sitter-go/assets/61237619/f271c92c-0f35-45ec-a655-e74eee51b806)

![image](https://github.com/tree-sitter/tree-sitter-go/assets/61237619/8489c099-31c4-4f9e-83ba-d67244f64dcd)

![image](https://github.com/tree-sitter/tree-sitter-go/assets/61237619/d425619f-0d0d-4a50-9c4d-588d42813090)

Not sure if is possible but would be good to have it to be parsed as constant.

Also I have no clue how to implement that, but maybe with some direction and guidance I can start working on that.

**Comment by amaanq** [comment]
that's not tree-sitter's job but rather an lsp to provide semantic tokens
