### ISSUE TITLE
Issue with Highlighting Function Parameters Inside the Function

### ISSUE THREAD

**Issue by gustavocmaciel** [tree-sitter/tree-sitter-go#134]
It seems to have an issue with the highlighting functionality, specifically related to the highlighting of function parameters within the function body. While the current implementation correctly highlights the parameter declaration, it fails to highlight the parameter when used inside the function.

**Go** example:
<img width="385" alt="image" src="https://github.com/tree-sitter/tree-sitter-go/assets/66797203/6fd2fc51-aa72-49a2-b7f7-c035881450c5">

I believe it should highlight function parameters consistently, both in the function declaration and within the function body. This behavior is observed in other languages like Rust.

**Rust** example:
<img width="404" alt="image" src="https://github.com/tree-sitter/tree-sitter-go/assets/66797203/b6969853-115b-4615-b756-21d48fcfeecc">

I suspect the problem arises because the current implementation only includes a node for `parameter_declaration`, which may be causing the issue. I have noticed that in languages like Rust, a node named `parameter` is used, which I assume it might be more generic (?) and may be contributing to the correct highlighting behavior. 

It would be beneficial to explore the possibility of implementing a similar approach for Go as well.

Thank you for your attention to this matter. Let me know if any additional information or clarification is needed.

**Comment by amaanq** [comment]
This is a complete misunderstanding of how your tool (probably neovim?) works, tree-sitter does not provide this behavior out of the box, what you're experiencing in Rust is probably lsp semantic tokens since rust-analyzer is a lot more powerful than gopls. You would want tree-sitter based tagging/locals, the grammar does *NOT* influence that at all.

**Comment by gustavocmaciel** [comment]
So I've been investigating gopls semantic tokens and found out that this `semanticTokens = true` should be included in lsp configuration file:
```lua
      lspconfig.gopls.setup({
        capabilities = capabilities,
        on_attach = on_attach,
        settings = {
          gopls = {
            completeUnimported = true,
            gofumpt = true,
            staticcheck = true,
            semanticTokens = true,
          },
        },
        filetypes = { "go", "gomod" },
        flags = {
          debounce_text_changes = 150,
        },
      })

```

Now it works as expected:

<img width="346" alt="image" src="https://github.com/tree-sitter/tree-sitter-go/assets/66797203/8d657704-024e-49ff-8a99-a4051f9b5aef">

Thanks for the clarification

**Comment by amaanq** [comment]
no problem, glad you got it solved.
