### ISSUE TITLE
Possible Bug with Generics

### ISSUE THREAD

**Issue by clseibold** [tree-sitter/tree-sitter-go#140]
I was using Zed and noticed that the types in this struct aren't highlighted correctly. Looks like there's an ERROR for the field right after the generic:
![image](https://github.com/tree-sitter/tree-sitter-go/assets/139164042/fd044677-f501-4d05-968b-52eb2b416489)

I do not know if this is a problem with the grammar or Zed itself, so posting it here just in case.

**Comment by amaanq** [comment]
pretty sure i fixed this in the latest version, zed needs to update tree-sitter-go.

**Comment by clseibold** [comment]
Ok, thanks.
