### ISSUE TITLE
Failure at initialization of go-ts-mode with recent Emacs

### ISSUE THREAD

**Issue by dunric** [tree-sitter/tree-sitter-go#141]
I've successfully installed `libtree-sitter-go.so` lib from current master branch.

Attempt to start `go-ts-mode` fails with

> Error during redisplay: (jit-lock-function 202) signaled (treesit-query-error "Node type error at" 150 "(function_declaration name: (identifier) @font-lock-function-name-face) (method_declaration name: (field_identifier) @font-lock-function-name-face) (method_spec name: (field_identifier) @font-lock-function-name-face) (field_declaration name: (field_identifier) @font-lock-property-name-face) (parameter_declaration name: (identifier) @font-lock-variable-name-face) (short_var_declaration left: (expression_list (identifier) @font-lock-variable-name-face (\",\" (identifier) @font-lock-variable-name-face) *)) (var_spec name: (identifier) @font-lock-variable-name-face (\",\" name: (identifier) @font-lock-variable-name-face) *)"

GNU Emacs 29.3 on x86_64 Linux
go-mode.el version 1.6.0
tree-sitter-go current
tree-sitter-gomod current

**Comment by ObserverOfTime** [comment]
"Node type error at" means that go-ts-mode needs to be updated.

**Comment by MacMcIrish** [comment]
Unless I misunderstand, `go-ts-mode` is packaged with emacs. GNU emacs 29.3 is the updated version. I don't think closing this issue was appropriate.

Rolling back to `v0.20.0` fixed the issue for me.

Copying the quick fix for others that installed via `treesit-install-language-grammar` like myself on fresh installs of emacs:

```bash
git clone https://github.com/tree-sitter/tree-sitter-go && cd tree-sitter-go
git checkout v0.20.0
tree-sitter generate
tree-sitter build
# mac specific instructions
rm ~/.emacs.d/tree-sitter/libtree-sitter-go.dylib
cp go.dylib ~/.emacs.d/tree-sitter/libtree-sitter-go.dylib
```

And restart emacs.

**Comment by dunric** [comment]
@MacMcIrish Good find, stock `go-ts-mode` is out of sync with current parser lib and it causes such issues.

However you don't need retire to manual compilation of older version. Just pass to `treesit-install-language-grammar` function desired tag/branch in interactive mode. In this case `v0.20.0` and it will rebuild it automatically.

Syntax highlighting of current `go-ts-mode` with `tree-sitter-go` parser seems to lack some features available in normal `go-mode` like distinguished rendering of method/function names and module identifiers.
