### ISSUE TITLE
Query with multiple variable identifiers (var + const)

### ISSUE THREAD

**Issue by matansha** [tree-sitter/tree-sitter-go#142]
Hi,

I trying to query all the variables in my program, but it seems when we have multiple variables in var or const it's not catch them.

For example from tree sitter playground:
<img width="718" alt="image" src="https://github.com/tree-sitter/tree-sitter-go/assets/4048539/b7af22f8-a08e-4a97-9d75-3ad177bb48bd">

It seems we have multiple fields in the same name (name) that enforce me to create N queries for N variable name declarations.

Thanks!

**Comment by amaanq** [comment]
use `name: (_)+` - https://tree-sitter.github.io/tree-sitter/using-parsers#quantification-operators

**Comment by matansha** [comment]
As you can see it didn't works
<img width="709" alt="image" src="https://github.com/tree-sitter/tree-sitter-go/assets/4048539/cb6641bb-99b6-45dc-a1d4-456ad24d4de5">

Also, in many other languages, i didn't see the same behavior like this when we have same fields

**Comment by amaanq** [comment]
oh - yeah that doesn't work because the field seems to include the commas too - and `(_)` will match any *named* nodes, not these commas. this should be fixed since commas are not a name

**Comment by matansha** [comment]
Do you have any time estimation when it going to be fixed?
Also, why not replace the multiple "name" with `identifiers_list` like the `expression_list`
