### ISSUE TITLE
New release to support tree-sitter 0.21 or 0.22

### ISSUE THREAD

**Issue by wetneb** [tree-sitter/tree-sitter-go#143]
The latest release (0.20) of tree-sitter-go requires `tree-sitter = ">= 0.20, < 0.21"`.
Since then, tree-sitter 0.21 and 0.22 have been released.

So it could be nice to publish a new version  of tree-sitter-go which would be compatible with those newer versions.
Looking at the current master branch, we have `tree-sitter = ">=0.21.0"`, so perhaps just making a release from the current master branch would suffice.

Thanks for your work on this crate!

**Comment by amaanq** [comment]
https://crates.io/crates/tree-sitter-go/0.21.0/ has been out since April.

**Comment by wetneb** [comment]
Nice, I have been mislead by the latest GitHub release which is older. Maybe it'd be worth creating a GitHub release for 0.21.0?

**Comment by amaanq** [comment]
ah, that's a little too much maintenance burden for me to do manually across every grammar, unless our CI adds that whenever I push a tagged commit - I'll think about adding that but very low priority
