### ISSUE TITLE
What query to highlight package identifiers in qualified function calls?

### ISSUE THREAD

**Issue by lvignoli** [tree-sitter/tree-sitter-go#144]
Hello!

I would like to highlight package identifiers in package qualified function calls.
Using this grammar, what would be the correct query to do so? Is it even possible with the current grammar?

---

Example:

```go
package main

import (
	"fmt"
	"time"
)

func main(){
	<fmt>.Println("hello") // Highlights package `fmt` in this function call. 
	t := time.Time{} // Does not highlight package `time`, can be done using qualified_type.
	_ = t.Date() // But does _not_ highlight object `t` in this method call.
}
```

I tried the following query:
```clojure
(call_expression
  function: (selector_expression
    operand: (package_identifier) @namespace)
```
but get the error `Bad pattern structure at offset 54: 'operand: (package_identifier) @type))'...`.

An indeed this cannot work: the corresponding AST chunk does not specialise the prefix to a [`package_identifier`](https://github.com/tree-sitter/tree-sitter-go/blob/7ee8d928db5202f6831a78f8112fd693bf69f98b/grammar.js#L846), but only an `identifier`:
```text
call_expression [8, 1] - [8, 21]
    function: selector_expression [8, 1] - [8, 12]
        operand: identifier [8, 1] - [8, 4]
        field: field_identifier [8, 5] - [8, 12]
    arguments: argument_list [8, 12] - [8, 21]
        interpreted_string_literal [8, 13] - [8, 20]
```
But matching against `identifier` would highlight objects in method calls as well.

In contrast, qualified types are easily matched by the following query:
```Clojure
(qualified_type
    package: (package_identifier) @namespace)
```

**Comment by amaanq** [comment]
There is no distinction at the syntax level whether it is a package_identifier or identifier (this is not tree-sitter's job), you'd need semantic analysis on top of that to figure that out - so you will have to match identifiers that could be a package, or could be an object.

**Comment by lvignoli** [comment]
Thanks @amaanq for this prompt reply.

So, if I understand correctly, it's not possible to highlight package identifiers in qualified function calls with tree-sitter queries, even using predicates. One needs the list of declared packages, and that requires further analysis on top of AST.

Do you have any pointers on where to start?
I'll close the issue.

**Comment by amaanq** [comment]
Yeah, what you're looking for, highlighting-wise, is semantic tokens if you want proper highlighting that distinguishes between usage of a package or object. You could take a look into github's [stack graphs](https://github.com/github/stack-graphs) for an implementation on top of tree-sitter that tracks name resolution
