### ISSUE TITLE
Highlighting multidimensional arrays and slices

### ISSUE THREAD

**Issue by sayMuFaSa** [tree-sitter/tree-sitter-go#148]
This parser highlights multidimensional array and also variables in brackets as a type when is used with variables to get specific item in the array.
Example code:
```
package main

func main() {
	var cells [3][2]int;
	var i = 90;
	var j = 20;

	cells[i][j] = 90;
}
```
The parser highlights variables cells, i and j as types on the line 8.

**Comment by amaanq** [comment]
this repo is for the parser, highlights are implementation dependent, unless using the *cli* with the queries *here*.
