### ISSUE TITLE
Raw strings mis-parsed as of 528f3fc

### ISSUE THREAD

**Issue by smoelius** [tree-sitter/tree-sitter-go#155]
I think 528f3fc may have introduced a bug regarding raw strings.

Consider this Go code:
```go
func TestRawString(t *testing.T) {
	s := `//`
}
```
And this query:
```
(block
    "{"
    (_statement) @statement
    "}"
) @block
```
At 47e8b1f (528f3fc's parent), the assignment to `s` is highlighted. At 528f3fc, it is not.

The above example is reduced from: https://github.com/minio/minio/blob/0e9854372ef81402fd3e81e0f7bbe852896f2ef7/cmd/object-api-utils_test.go#L268

**Comment by amaanq** [comment]
Sorry about that, bad oversight on my part. Should be fixed now & I've cut a release

**Comment by smoelius** [comment]
> Sorry about that, bad oversight on my part. Should be fixed now & I've cut a release

Please don't be sorry. Thank you for the fix, which is working great! 🙏
