### ISSUE TITLE
Parameter list is not parsed correctly. 

### ISSUE THREAD

**Issue by purpuregecko** [tree-sitter/tree-sitter-go#24]
Pls, look at the example:
```go
type A struct{}

func (A)Example(A)(A) {}
```
In atom using tree-sitter  `A` in function declaration is not highlited as type. If I understand right it parsed as parameter name. [Function declaration go spec](https://golang.org/ref/spec#Function_declarations).

**Comment by maxbrunsfeld** [comment]
Thanks for the report. This case should now be parsed correctly. There are still some cases where we can't tell types from parameter names, like this:

```go
func test(person, name string) {
}
```

In that case, we can't tell if `person` is a type (unnamed parameter) or a parameter of type `string`. For now, we will assume that it is *not* a type.

**Comment by purpuregecko** [comment]
@maxbrunsfeld in this case person always is name. If one name used all arguments must be with name  or all parameters should be unnamed.

**Comment by maxbrunsfeld** [comment]
Oh ok great, thanks for pointing that out. I think the new behavior will always be correct then, unless I'm missing something.

**Comment by maxbrunsfeld** [comment]
I think we're doing it right now:

![parameters](https://user-images.githubusercontent.com/326587/36278515-f3012204-1248-11e8-96f5-49f9c2b3d073.gif)
