### ISSUE TITLE
Remove golang/go and moby/moby submodules.

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-go#29]
These bloat .git directories in a big, big way.

**Comment by maxbrunsfeld** [comment]
Yeah we probably should have added a bash script that fetched those repos for testing purposes, rather than git submodules. That way you could ‘fit submodule init —recursive’ and not get unneeded objects.

**Comment by maxbrunsfeld** [comment]
This was fixed by https://github.com/tree-sitter/tree-sitter-go/pull/30.
