### ISSUE TITLE
Investigate performance characteristics

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-go#37]
We’ve found in production that the go parser is surprisingly slow: it can pull 1.25 MB/sec, which is no slouch, but in contrast, a language like C#, which has _much_ more syntax, is nearly twice as fast. This isn’t a showstopper, but it might be interesting to look into exactly why this is!

**Comment by patrickt** [comment]
This parser appears to handle Unicode characters correctly; might be it?

**Comment by amaanq** [comment]
I'm getting ~9100 bytes/ms aka 9mb/s for Go and ~8000 bytes/ms aka 8mb/s for C# on my machine, Go seems to be doing slightly better than C# currently, so closing
