### ISSUE TITLE
"source_file" allows "BLANK" to follow "_top_level_declaration"

### ISSUE THREAD

**Issue by berchn** [tree-sitter/tree-sitter-go#46]
`source_file` allows `BLANK` to follow `_top_level_declaration` in `src/grammar.json`. This is resulting in an AST that doesn't appear to be valid. The following code parses without error or the addition of any zero-width tokens, but it does not compile:

```go
package a package b package c package d
```
This is due to the `optional(terminator)` in the relevant section of the `source_file` rule in `grammar.js`. Is this intended?

**Comment by adonovan** [comment]
The optionality should be removed here:
https://github.com/tree-sitter/tree-sitter-go/blob/07d722831382a043b16547b6d9202f3da07f3cb3/grammar.js#L107
I suspect in practice it's less trouble to make the parsers overgenerous in what they accept than to have to analyze the dark corners perfectly (where compilers often have bugs too).
