### ISSUE TITLE
`package_identifier` is missing in some cases

### ISSUE THREAD

**Issue by 2nishantg** [tree-sitter/tree-sitter-go#51]
For the following snippet
```go
package main

import "context"

func foo(ctx context.Context) {
	ctx := context.WithCancel(ctx)
}
```
the tree-sitter AST is 
```source_file:
  package_clause:
    package_identifier:
  import_declaration:
    import_spec:
      interpreted_string_literal:
  function_declaration:
    identifier:
    parameter_list:
      parameter_declaration:
        identifier:
        qualified_type:
          package_identifier:
          type_identifier:
    block:
      short_var_declaration:
        expression_list:
          identifier:
        expression_list:
          call_expression:
            selector_expression:
              identifier:
              field_identifier:
            argument_list:
              identifier:
```
For the function call `context.WithCancel`, `package_identifier` is not emitted but its emitted for parameter.

I am using tree-sitter via https://github.com/emacs-tree-sitter, please let me know if you want me to test this in some other way or if you require some other info.

**Comment by maxbrunsfeld** [comment]
Yeah, `context.Context` is intentionally treated differently than `context.WithCancel`, because one is a type and one is an expression. We parse `context.WithCancel` as a `selector_expression`, because there's no way to know whether `context` is a package name or the name of a local variable (without maintaining a symbol table).

**Comment by ameddin73** [comment]
Any progress on this? I'm using nvim-treesitter and I'd like to see package names highlighted like in Goland.
