### ISSUE TITLE
Function call parsed as a Type conversion

### ISSUE THREAD

**Issue by aryx** [tree-sitter/tree-sitter-go#53]
From https://github.com/returntocorp/semgrep/issues/3993

this program:
```
_ := os.GetEnv("Test")
```
without the ending newline is parsed as a type conversion instead of a regular function call.

**Comment by adonovan** [comment]
Perhaps it is a type conversion: you can't tell without seeing whether package `os` defines `type GetEnv string` or func GetEnv(string) string`, and the parser is not privy to that information.

**Comment by aryx** [comment]
Still it's weird that a newline has an impact on how this thing is parsed.

**Comment by aryx** [comment]
And in any case, because tree-sitter does not have the information, it should parse it as a function call, not a cast.
It should return a Cast node when we know for sure the thing is a type, as in  _ := int(3)

**Comment by dominikh** [comment]
@aryx 
>  It should return a Cast node when we know for sure the thing is a type, as in _ := int(3)

Do note that even in that case, `int` could just as easily refer to a function that is shadowing the predeclared type `int`.
