### ISSUE TITLE
builtin functions?

### ISSUE THREAD

**Issue by jimeh** [tree-sitter/tree-sitter-go#55]
It doesn't look like Go's built-in functions are defined in tree-sitter-go.

For reference, built-in function functions seem like they're fined here in Go's source: https://github.com/golang/go/blob/master/src/builtin/builtin.go

**Comment by amaanq** [comment]
This can be accomplished w/ queries

**Comment by jimeh** [comment]
@amaanq Apologies, I forgot to close this a while back when #96 was merged.

**Comment by amaanq** [comment]
no worries!
