### ISSUE TITLE
Support direct constraint elements outside `interface{...}` in type parameter lists

### ISSUE THREAD

**Issue by fzipp** [tree-sitter/tree-sitter-go#62]
This code reports errors on the [tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground):

```
func f[A int|string, B ~int, C ~int|~string]() {
}
```

```
source_file [0, 0] - [2, 0]
  function_declaration [0, 0] - [1, 1]
    name: identifier [0, 5] - [0, 6]
    type_parameters: type_parameter_list [0, 6] - [0, 44]
      parameter_declaration [0, 7] - [0, 19]
        name: identifier [0, 7] - [0, 8]
        ERROR [0, 9] - [0, 13]
          identifier [0, 9] - [0, 12]
        type: type_identifier [0, 13] - [0, 19]
      parameter_declaration [0, 21] - [0, 27]
        name: identifier [0, 21] - [0, 22]
        ERROR [0, 23] - [0, 24]
        type: type_identifier [0, 24] - [0, 27]
      parameter_declaration [0, 29] - [0, 43]
        name: identifier [0, 29] - [0, 30]
        ERROR [0, 31] - [0, 37]
          identifier [0, 32] - [0, 35]
        type: type_identifier [0, 37] - [0, 43]
    parameters: parameter_list [0, 44] - [0, 46]
    body: block [0, 47] - [1, 1]
```

But it is valid according to the Go 1.18 spec: https://tip.golang.org/ref/spec#Type_constraints

> If the constraint is an interface literal containing exactly one embedded type element interface{E}, in a type parameter list the enclosing interface{ … } may be omitted for convenience:
> 
> ```
> [T *P]                             // = [T interface{*P}]
> [T ~int]                           // = [T interface{~int}]
> [T int|string]                     // = [T interface{int|string}]
> ```

**Comment by adonovan** [comment]
The type_parameter_list production seems not to be aware of constraints; it uses the same logic as ordinary parameters: 

https://github.com/tree-sitter/tree-sitter-go/blob/07d722831382a043b16547b6d9202f3da07f3cb3/grammar.js#L219-L222
