### ISSUE TITLE
"any" type highlight

### ISSUE THREAD

**Issue by vcraescu** [tree-sitter/tree-sitter-go#83]
I don't know if there is a problem with Neovim or with the tree-sitter but apparently, the `any` type is incorrectly highlighted.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/941660/178109528-f0911ca1-1ec1-4df7-b2da-122522256767.png">

In TSPlayground it looks like the `TSTypeBuiltin` highlight is applied but for some reason, `TSType` highlight is used.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/941660/178109606-7c8a7677-c870-4b15-bf15-e98b94d32d08.png">

**Comment by fioncat** [comment]
I think `any` and `comparable` should be highlighted, they are new predeclared identifiers since go1.18, [release note](https://go.dev/doc/go1.18#generics):

> The new [predeclared identifier](https://go.dev/ref/spec#Predeclared_identifiers) any is an alias for the empty interface. It may be used instead of interface{}.
> The new [predeclared identifier](https://go.dev/ref/spec#Predeclared_identifiers) comparable is an interface that denotes the set of all types which can be compared using == or !=. It may only be used as (or embedded in) a type constraint.

**Comment by vcraescu** [comment]
yeah
