### ISSUE TITLE
How can i get the params with type

### ISSUE THREAD

**Issue by glepnir** [tree-sitter/tree-sitter-go#84]
I want get function name,param name param type , currently I write this .it just work with function params with builtin type. if use a package.function type that doesn't work or pointer type. I can add `(pointer_type) (package_type)` . Looks like I have to write multiple expressions? I'm not very familiar with sexpr. Thanks

```
(function_declaration
  (identifier) @func.name
  (parameter_list
      (parameter_declaration
        (identifier) @param.name
        ("," @param.separator (_))*
        (type_identifier) @param.type)))

```

**Comment by amaanq** [comment]
closing as (assumingly) completed, question is a little unclear
