### ISSUE TITLE
Add support for Go templates

### ISSUE THREAD

**Issue by devkvlt** [tree-sitter/tree-sitter-go#93]

**Comment by bigjazzsound** [comment]
I would also like to see this get implemented.

Helm uses go templates inside yaml files. Unless the templates are quoted, the yaml parser does not know how to handle them. Hopefully it would be possible to inject go templates into these yaml files.

**Comment by amaanq** [comment]
This should be done by creating a gotmpl grammar and injecting it into this one.

**Comment by amaanq** [comment]
Ah right, we can use `not planned`

**Comment by YeisonAndreyLiCe** [comment]
https://github.com/ngalaiko/tree-sitter-go-template
